apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rm-postgresql-app-pvc
  namespace: redmine
spec:
  storageClassName: gluster-heketi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
