apiVersion: v1
kind: ReplicationController
metadata:
  name: postgresql
  namespace: gitlab
spec:
  replicas: 1
  selector:
    name: postgresql
  template:
    metadata:
      name: postgresql
      labels:
        name: postgresql
    spec:
      containers:
        - name: postgresql
          image: sameersbn/postgresql:10
          env:
            - name: TZ
              value: Asia/Seoul
            - name: GITLAB_TIMEZONE
              value: Seoul

            - name: DB_USER
              value: gitlab
            - name: DB_PASS
              value: qwer1234
            - name: DB_NAME
              value: gitlab_production
            - name: DB_EXTENSION
              value: pg_trgm,btree_gist
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: app-db-pv
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -U
                - postgres
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -U
                - postgres
            initialDelaySeconds: 5
            timeoutSeconds: 1
      volumes:
        - name: app-db-pv
          persistentVolumeClaim:
            claimName: app-db-pvc